rental_property:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: <Your Snowflake Account>   # add region if required

      user: dbt
      role: TRANSFORM               # using TRANSFORM role
      warehouse: COMPUTE_WH
      database: RENTAL_PROPERTY
      schema: development         # fixed typo
      threads: 1

      private_key: < Your Private Key >
      private_key_passphrase: admin

      client_session_keep_alive: false
